stuManage/config/routes.rb
Rails.application.routes.draw do
  resources :s_classes
  resources :grades
  get "login" => 'session#new'
  post "login" => 'session#login'
  get "logout" => 'session#logout'

  resources :users
  root 'welcome#index'
    # root 'users#register'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

stuManage/app/controllers/s_classes_controller.rb
class SClassesController < ApplicationController
  before_action :set_s_class, only: [:show, :edit, :update, :destroy]

  # GET /s_classes
  # GET /s_classes.json
  def index
    @s_classes = SClass.all
  end

  # GET /s_classes/1
  # GET /s_classes/1.json
  def show
  end

  # GET /s_classes/new
  def new
    @s_class = SClass.new
  end

  # GET /s_classes/1/edit
  def edit
  end

  # POST /s_classes
  # POST /s_classes.json
  def create
    @s_class = SClass.new(s_class_params)

    respond_to do |format|
      if @s_class.save
        format.html { redirect_to @s_class, notice: 'S class was successfully created.' }
        format.json { render :show, status: :created, location: @s_class }
      else
        format.html { render :new }
        format.json { render json: @s_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /s_classes/1
  # PATCH/PUT /s_classes/1.json
  def update
    respond_to do |format|
      if @s_class.update(s_class_params)
        format.html { redirect_to @s_class, notice: 'S class was successfully updated.' }
        format.json { render :show, status: :ok, location: @s_class }
      else
        format.html { render :edit }
        format.json { render json: @s_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /s_classes/1
  # DELETE /s_classes/1.json
  def destroy
    @s_class.destroy
    respond_to do |format|
      format.html { redirect_to s_classes_url, notice: 'S class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_s_class
      @s_class = SClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def s_class_params
      params.require(:s_class).permit(:class_name, :teacher_id, :year, :grade_id)
    end
end

stuManage/app/helpers/s_classes_helper.rb
module SClassesHelper
end

stuManage/app/views/s_classes/_form.html.erb
<%= form_with(model: s_class, local: true) do |form| %>
  <% if s_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(s_class.errors.count, "error") %> prohibited this s_class from being saved:</h2>

      <ul>
      <% s_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :class_name %>
    <%= form.text_field :class_name, id: :s_class_class_name %>
  </div>

  <div class="field">
    <%= form.label :teacher_id %>
    <%= form.number_field :teacher_id, id: :s_class_teacher_id %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year, id: :s_class_year %>
  </div>

  <div class="field">
    <%= form.label :grade_id %>
    <%= form.number_field :grade_id, id: :s_class_grade_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

stuManage/app/views/s_classes/edit.html.erb
<h1>Editing S Class</h1>

<%= render 'form', s_class: @s_class %>

<%= link_to 'Show', @s_class %> |
<%= link_to 'Back', s_classes_path %>

stuManage/app/views/s_classes/index.html.erb
<p id="notice"><%= notice %></p>

<%#= link_to 'New S Class', new_s_class_path %>

<p id="notice"><%= notice %></p>
<div class="container">

  <p>
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">Classes</h1>
    </div>
  </div>
  <label for="">List Users</label>
  <div class="col-lg-12 form-group" align="right">
    <%= link_to 'New Class',new_s_class_path, :class => "btn btn-success button-function"%>
  </div>
  <table id="table-collapse" class="table table-bordered col-lg-7 table-user">
    <thead>
    <tr>
      <!-- <th>Id</th> -->
      <th>Class name</th>
      <!-- <th>Password hash</th> -->
      <th>Teacher</th>
      <th>Year</th>
      <th>Grade</th>
      <th></th>
      <!-- <th colspan="3"></th> -->
    </tr>
    </thead>p

    <tbody>
    <% @s_classes.each do |s_class| %>
      <tr>
        <!-- <td><%= s_class.id %></td> -->
        <!-- <td><%= s_class.password_digest %></td> -->
        <td><%= s_class.class_name %></td>
        <td><%= s_class.teacher_id %></td>
        <td><%= s_class.year == 0 ? 'Student' : s_class.role == 1 ? 'Teacher' : 'Admin'%></td>
        <td><%= s_class.grade_id %></td>
        <td class="text-center">
          <%= link_to 'Show', s_class, :class => 'btn btn-sm btn-info button-function button-width'%>
          <%= link_to 'Edit', edit_s_class_path(s_class), :class => 'btn btn-sm btn-warning button-function button-width' %>
          <%= link_to 'Destroy', s_class, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger button-function button-width' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<!-- <%#= link_to 'New Class', new_s_class_path %> -->

stuManage/app/views/s_classes/new.html.erb
<h1>New S Class</h1>

<%= render 'form', s_class: @s_class %>

<%= link_to 'Back', s_classes_path %>

stuManage/app/views/s_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class name:</strong>
  <%= @s_class.class_name %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @s_class.teacher_id %>
</p>

<p>
  <strong>Year:</strong>
  <%= @s_class.year %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @s_class.grade_id %>
</p>

<%= link_to 'Edit', edit_s_class_path(@s_class) %> |
<%= link_to 'Back', s_classes_path %>