stuManage/config/routes.rb
Rails.application.routes.draw do
  resources :s_classes
  resources :grades
  get "login" => 'session#new'
  post "login" => 'session#login'
  get "logout" => 'session#logout'

  resources :users
  root 'welcome#index'
    # root 'users#register'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

stuManage/app/models/grade.rb
class Grade < ApplicationRecord
end

stuManage/app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:grade_name)
    end
end

stuManage/app/helpers/grades_helper.rb
module GradesHelper
end

stuManage/app/views/grades/_form.html.erb
<%= form_with(model: grade, local: true) do |form| %>
  <% if grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :grade_name %>
    <%= form.number_field :grade_name, id: :grade_grade_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

stuManage/app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

stuManage/app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<%#= link_to 'New Grade', new_grade_path %>

<p id="notice"><%= notice %></p>
<div class="container">

  <p>
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">Grades</h1>
    </div>
  </div>
  <label for="">List Grade</label>
  <div class="col-lg-12 form-group" align="right">
    <%= link_to 'New Grade',new_grade_path, :class => "btn btn-success button-function"%>
  </div>
  <table id="table-collapse" class="table table-bordered col-lg-7 table-user">
    <thead>
    <tr>
      <!-- <th>Id</th> -->
      <th>Grade</th>
      <!-- <th>Password hash</th> -->
      <!--<th>Full name</th>-->
      <!--<th>Type</th>-->
      <!--<th>Class</th>-->
      <th></th>
      <!-- <th colspan="3"></th> -->
    </tr>
    </thead>

    <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <!-- <td><#%= grade.id %></td> -->
        <!-- <td><#%= grade.password_digest %></td> -->
        <!--<td><#%= grade.full_name %></td>-->
        <!--<td><#%= grade.role == 0 ? 'Student' : grade.role == 1 ? 'Teacher' : 'Admin'%></td>-->
        <!--<td><#%= grade.class_id %></td>-->
        <td><%= grade.grade_name %></td>
        <td class="text-center">
          <%= link_to 'Show', grade, :class => 'btn btn-sm btn-info button-function button-width'%>
          <%= link_to 'Edit', edit_grade_path(grade), :class => 'btn btn-sm btn-warning button-function button-width' %>
          <%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger button-function button-width' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<!-- <%= link_to 'New User', new_user_path %> -->

stuManage/app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Back', grades_path %>

stuManage/app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grade name:</strong>
  <%= @grade.grade_name %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>