stuManage/config/routes.rb
Rails.application.routes.draw do
  resources :s_classes
  resources :grades
  get "login" => 'session#new'
  post "login" => 'session#login'
  get "logout" => 'session#logout'

  resources :users
  root 'welcome#index'
    # root 'users#register'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

stuManage/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

stuManage/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # if logged_in?
    #   @user = User.find(session[:user_id])
    #   render plain: @user
    # else
    #   render plain: "Loggedout"
    #   @user = User.find(params[:id])
    # end
    @user = User.find_by id: params[:id]
  end

  # GET /users/new
  def new
    @current_page = 'register'
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @current_page = 'edit'
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # redirect_to @user
        # format.html { redirect_to users_path, notice: 'User was successfully created !!!.' }
        format.html { redirect_to @user, notice: 'User was successfully created !!!.' }
        format.json { render :show, status: :created, location: @user }
        # format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    if logged_in?
      @user = User.find(session[:user_id])
      # render plain: @user
    else
      # render plain: "Loggedout"
      @user = User.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:id, :user_name, :password, :password_confirmation, :full_name, :role, :class_id)
  end
end

stuManage/app/helpers/users_helper.rb
module UsersHelper
end

stuManage/app/views/users/_form.html.erb
 <div class="container container-center">
<%= form_with(model: user, local: true) do |form| %>
<% if user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<form class="form-horizontal">
  <div class="register-field">
    <div class="form-group ">
      <%= form.label :user_name, class: "control-label" %>
      <%= form.text_field :user_name, id: :user_user_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password, class: "control-label" %>
      <%= form.password_field :password, id: :user_password, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation, class: "control-label" %>
      <%= form.password_field :password_confirmation, id: :user_password_confirmation, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :full_name, class: "control-label" %>
      <%= form.text_field :full_name, id: :user_full_name, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :role, class: "control-label" %>
      <!--<#%= form.text_field :role, id: :user_role, class: "form-control"  %>-->
      <%= form.select :role,[['Student',0],['Teacher',1],['Admin',2]],{}, :class => 'form-control'%>
    </div>

    <div class="form-group">
      <%= form.label :class_id, class: "control-label" %>
      <%= form.text_field :class_id, id: :user_class_id, class: "form-control"  %>
    </div>
  <!--<div class="col-lg-offset-3 col-lg-3">-->
    <div class="form-group">
      <!--<#%= form.submit current_page?(:controller => 'users',:action => 'edit') ? "Update" : "Register", :class => 'col-lg-7 btn btn-primary btn-block button'%>-->
      <%= form.submit @current_page == 'edit' ? "Update" : "Register", :class => 'col-lg-7 btn btn-primary btn-block button'%>
    </div>
  <!--</div>-->
  </div>

</form>
<% end %>
 </div>

stuManage/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

stuManage/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

<p>
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">LOGIN APP</h1>
    </div>
    <div class="col-lg-12 form-group">
      <label for="">Welcome</label>
      <%= link_to current_user.full_name, user_path(current_user) %>
    </div>
  </div>
<label for="">List Users</label>
<div class="col-lg-12 form-group" align="right">
  <%= link_to 'New User',new_user_path, :class => "btn btn-success button-function"%>
</div>
<table id="table-collapse" class="table table-bordered col-lg-7 table-user">
  <thead>
    <tr>
      <!-- <th>Id</th> -->
      <th>User name</th>
      <!-- <th>Password hash</th> -->
      <th>Full name</th>
      <th>Type</th>
      <th>Class</th>
      <th></th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <!-- <td><%= user.id %></td> -->
        <!-- <td><%= user.password_digest %></td> -->
        <td><%= user.user_name %></td>
        <td><%= user.full_name %></td>
        <td><%= user.role == 0 ? 'Student' : user.role == 1 ? 'Teacher' : 'Admin'%></td>
        <td><%= user.class_id %></td>
        <td class="text-center">
          <%= link_to 'Show', user, :class => 'btn btn-sm btn-info button-function button-width'%>
          <%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-sm btn-warning button-function button-width' %>
          <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger button-function button-width' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<!-- <%= link_to 'New User', new_user_path %> -->

stuManage/app/views/users/new.html.erb
<div class="container">
  <h1 align="center">New User</h1>

  <%= render 'form', user: @user %>
<!--<div class="col-lg-offset-3 col-lg-3">-->
  <!--<div class="text-center">-->
    <!--<#%= link_to 'Quay lại', users_path, :class => 'btn btn-primary btn-block button'%>-->
  <!--</div>-->
  <!--</div>-->
</div>

stuManage/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<!--<p>-->
  <!--<strong>Id:</strong>-->
  <!--<#%= @user.id %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>User name:</strong>-->
  <!--<#%= @user.user_name %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Password hash:</strong>-->
  <!--<#%= '********' %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Full name:</strong>-->
  <!--<#%= @user.full_name %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Type:</strong>-->
  <!--<#%= @user.role %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Class:</strong>-->
  <!--<#%= @user.class_id %>-->
<!--</p>-->

<%#= link_to 'Edit', edit_user_path(@user) %>
<%#= link_to 'Back', users_path %>
<!--<%#= link_to 'Logout', logout_path %>-->

<!------ Include the above in your HEAD tag ---------->

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6">
      <div class="well well-sm">
        <div class="row">
          <div class="col-sm-6 col-md-4">
            <img src="http://placehold.it/380x500" alt="" class="img-rounded img-responsive" />
          </div>
          <div class="col-sm-6 col-md-8">
            <h4>
              <%=@user.full_name%> </h4>
            <small><cite title="San Francisco, USA"><%= @user.role == 0 ? 'Student' : @user.role == 1 ? 'Teacher' : 'Admin'  %></cite></small>
            <p>
              <i class="glyphicon glyphicon-envelope"></i>email@example.com
              <br />
              <i class="glyphicon glyphicon-globe"></i><a href="http://www.jquery2dotnet.com">www.jquery2dotnet.com</a>
              <br />
              <i class="glyphicon glyphicon-gift"></i>June 02, 1988</p>
            <!-- Split button -->
            <div class="btn-group">
              <button type="button" class="btn btn-primary">
                Social</button>
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span><span class="sr-only">Social</span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Twitter</a></li>
                <li><a href="https://plus.google.com/+Jquery2dotnet/posts">Google +</a></li>
                <li><a href="https://www.facebook.com/jquery2dotnet">Facebook</a></li>
                <li class="divider"></li>
                <li><a href="#">Github</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>