stuManage/config/routes.rb
Rails.application.routes.draw do
  resources :s_classes
  resources :grades
  get "login" => 'session#new'
  post "login" => 'session#login'
  get "logout" => 'session#logout'

  resources :users
  root 'welcome#index'
    # root 'users#register'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

stuManage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuManage</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="subnav">
  <!-- <ul> -->
  <% if logged_in? %>
    <div class="col-lg-1">
      <%= link_to "Profile", current_user, :class => 'current_class?(users_path) col-lg-2 btn btn-primary btn-block button' %>
    </div>
    <% if getRole == 2 %>
      <div class="col-lg-1">
        <%= link_to "Grades", grades_path, :class => 'current_class?(grades_path) col-lg-2 btn btn-primary btn-block button' %>
      </div>
      <div class="col-lg-1">
        <%= link_to "Classes", s_classes_path, :class => 'current_class?(s_classes_path) col-lg-2 btn btn-primary btn-block button' %>
      </div>
      <div class="col-lg-1">
        <%= link_to "Student", users_path, :class => 'current_class?(users_path) col-lg-2 btn btn-primary btn-block button' %>
      </div>
      <!-- <li><#%= link_to "Register", new_user_path, :class => current_class?(new_user_path)  %></li> -->
    <% end %>
    <div class="col-lg-1">
      <%= link_to "Back", users_path, :class => 'current_class?(users_path) col-lg-2 btn btn-primary btn-block button' %>
    </div>
    <div class="col-lg-1">
      <%= link_to "Logout", logout_path, :class => 'current_class?(logout_path) col-lg-2 btn btn-primary btn-block button', data: {confirm: "Are you sure want to log out ?"} %>
    </div>
  <% end %>
  <!-- </ul> -->
</nav>
<section class="content" style="min-height: auto;">
  <% flash.each do |key, value| %>
    <div class="row">
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    </div>
  <% end %>
</section>

  <%= yield %>
</body>
</html>